#ifndef DEFINES_H_
#define DEFINES_H_

#define MHZ_TO_HZ 1000000;
#define HACKRF_DEFAULT_SAMPLE_RATE (20*MHZ_TO_HZ)

#define DEFAULT_BUF_LENGTH		(1 * 16384)
#define MAXIMUM_OVERSAMPLE		16
#define MAXIMUM_BUF_LENGTH		(MAXIMUM_OVERSAMPLE * DEFAULT_BUF_LENGTH)
#define AUTO_GAIN			-100
#define BUFFER_DUMP			4096

#endif